using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Master.Entity.Const
{
    [ExcludeFromCodeCoverage]
    public static class PrequalCbo4D
    {
        public static readonly List<EnumItem> Vector =
        [
            new EnumItem { Id = 101, Descricao = "0101 - Oficiais generais das forças armadas" },
            new EnumItem { Id = 102, Descricao = "0102 - Oficiais das forças armadas" },
            new EnumItem { Id = 103, Descricao = "0103 - Praças das forças armadas" },
            new EnumItem { Id = 201, Descricao = "0201 - Oficiais superiores da polícia militar" },
            new EnumItem { Id = 202, Descricao = "0202 - Capitães da polícia militar" },
            new EnumItem { Id = 203, Descricao = "0203 - Tenentes da polícia militar" },
            new EnumItem { Id = 211, Descricao = "0211 - Subtenentes e sargentos da policia militar" },
            new EnumItem { Id = 212, Descricao = "0212 - Cabos e soldados da polícia militar" },
            new EnumItem { Id = 301, Descricao = "0301 - Oficiais superiores do corpo de bombeiros militar" },
            new EnumItem { Id = 302, Descricao = "0302 - Oficiais intermediários do corpo de bombeiros militar" },
            new EnumItem { Id = 303, Descricao = "0303 - Tenentes do corpo de bombeiros militar" },
            new EnumItem { Id = 311, Descricao = "0311 - Subtenentes e sargentos do corpo de bombeiros militar" },
            new EnumItem { Id = 312, Descricao = "0312 - Cabos e soldados do corpo de bombeiros militar" },
            new EnumItem { Id = 1111, Descricao = "1111 - Legisladores" },
            new EnumItem { Id = 1112, Descricao = "1112 - Dirigentes gerais da administração pública" },
            new EnumItem { Id = 1113, Descricao = "1113 - Magistrados" },
            new EnumItem { Id = 1114, Descricao = "1114 - Dirigentes do serviço público" },
            new EnumItem { Id = 1115, Descricao = "1115 - Gestores públicos" },
            new EnumItem { Id = 1130, Descricao = "1130 - Dirigentes de povos indígenas, de quilombolas e caiçaras" },
            new EnumItem { Id = 1141, Descricao = "1141 - Dirigentes de partidos políticos" },
            new EnumItem { Id = 1142, Descricao = "1142 - Dirigentes e administradores de entidades patronais e dos trabalhadores e de outros interesses sócioeconômicos" },
            new EnumItem { Id = 1143, Descricao = "1143 - Dirigentes e administradores de entidades religiosas" },
            new EnumItem { Id = 1144, Descricao = "1144 - Dirigentes e administradores de organizações da sociedade civil sem fins lucrativos" },
            new EnumItem { Id = 1210, Descricao = "1210 - Diretores gerais" },
            new EnumItem { Id = 1221, Descricao = "1221 - Diretores de produção e operações em empresa agropecuária, pesqueira , aqüícola e florestal" },
            new EnumItem { Id = 1222, Descricao = "1222 - Diretores de produção e operações em empresa da indústria extrativa, transformação e de serviços de utilidade pública" },
            new EnumItem { Id = 1223, Descricao = "1223 - Diretores de operações de obras em empresa de construção" },
            new EnumItem { Id = 1224, Descricao = "1224 - Diretores de operações em empresa do comércio" },
            new EnumItem { Id = 1225, Descricao = "1225 - Diretores de serviços de turismo, de alojamento e de alimentação" },
            new EnumItem { Id = 1226, Descricao = "1226 - Diretores de operações de serviços em empresa de armazenamento, de transporte e de telecomunicação" },
            new EnumItem { Id = 1227, Descricao = "1227 - Diretores de operações de serviços em instituição de intermediação financeira" },
            new EnumItem { Id = 1231, Descricao = "1231 - Diretores administrativos e financeiros" },
            new EnumItem { Id = 1232, Descricao = "1232 - Diretores de recursos humanos e relações de trabalho" },
            new EnumItem { Id = 1233, Descricao = "1233 - Diretores de comercialização e marketing" },
            new EnumItem { Id = 1234, Descricao = "1234 - Diretores de suprimentos e afins" },
            new EnumItem { Id = 1236, Descricao = "1236 - Diretores de tecnologia da informação" },
            new EnumItem { Id = 1237, Descricao = "1237 - Diretores de pesquisa e desenvolvimento" },
            new EnumItem { Id = 1238, Descricao = "1238 - Diretores de manutenção" },
            new EnumItem { Id = 1311, Descricao = "1311 - Diretores e gerentes de operações em empresa de serviços pessoais, sociais e culturais" },
            new EnumItem { Id = 1312, Descricao = "1312 - Gestores e especialistas de operações em empresas, secretarias e unidades de serviços de saúde" },
            new EnumItem { Id = 1313, Descricao = "1313 - Diretores e gerentes de instituição de serviços educacionais" },
            new EnumItem { Id = 1411, Descricao = "1411 - Gerentes de produção e operações em empresa agropecuária, pesqueira, aqüícola e florestal" },
            new EnumItem { Id = 1412, Descricao = "1412 - Gerentes de produção e operações em empresa da indústria extrativa, de transformação e de serviços de utilidade pública" },
            new EnumItem { Id = 1413, Descricao = "1413 - Gerentes de obras em empresa de construção" },
            new EnumItem { Id = 1414, Descricao = "1414 - Gerentes de operações comerciais e de assistência técnica" },
            new EnumItem { Id = 1415, Descricao = "1415 - Gerentes de operações de serviços em empresa de turismo, de alojamento e alimentação" },
            new EnumItem { Id = 1416, Descricao = "1416 - Gerentes de operações de serviços em empresa de transporte, de comunicação e de logística (armazenagem e distribuição)" },
            new EnumItem { Id = 1417, Descricao = "1417 - Gerentes de operações de serviços em instituição de intermediação financeira" },
            new EnumItem { Id = 1418, Descricao = "1418 - Gerentes operacionais da aviação civil" },
            new EnumItem { Id = 1421, Descricao = "1421 - Gerentes administrativos, financeiros, de riscos e afins" },
            new EnumItem { Id = 1422, Descricao = "1422 - Gerentes de recursos humanos e de relações do trabalho" },
            new EnumItem { Id = 1423, Descricao = "1423 - Gerentes de comercialização, marketing e comunicação" },
            new EnumItem { Id = 1424, Descricao = "1424 - Gerentes de suprimentos e afins" },
            new EnumItem { Id = 1425, Descricao = "1425 - Gerentes de tecnologia da informação" },
            new EnumItem { Id = 1426, Descricao = "1426 - Gerentes de pesquisa e desenvolvimento e afins" },
            new EnumItem { Id = 1427, Descricao = "1427 - Gerentes de manutenção e afins" },
            new EnumItem { Id = 2011, Descricao = "2011 - Profissionais da biotecnologia" },
            new EnumItem { Id = 2012, Descricao = "2012 - Profissionais da metrologia" },
            new EnumItem { Id = 2021, Descricao = "2021 - Engenheiros de controle e automação, engenheiros mecatrônicos e afins" },
            new EnumItem { Id = 2030, Descricao = "2030 - Pesquisadores das ciências biológicas" },
            new EnumItem { Id = 2031, Descricao = "2031 - Pesquisadores das ciências naturais e exatas" },
            new EnumItem { Id = 2032, Descricao = "2032 - Pesquisadores de engenharia e tecnologia" },
            new EnumItem { Id = 2033, Descricao = "2033 - Pesquisadores das ciências da saúde" },
            new EnumItem { Id = 2034, Descricao = "2034 - Pesquisadores das ciências da agricultura" },
            new EnumItem { Id = 2035, Descricao = "2035 - Pesquisadores das ciências sociais e humanas" },
            new EnumItem { Id = 2041, Descricao = "2041 - Peritos criminais e judiciais" },
            new EnumItem { Id = 2111, Descricao = "2111 - Profissionais da matemática" },
            new EnumItem { Id = 2112, Descricao = "2112 - Profissionais de estatística e afins" },
            new EnumItem { Id = 2122, Descricao = "2122 - Engenheiros em computação" },
            new EnumItem { Id = 2123, Descricao = "2123 - Administradores de tecnologia da informação" },
            new EnumItem { Id = 2124, Descricao = "2124 - Analistas de tecnologia da informação" },
            new EnumItem { Id = 2131, Descricao = "2131 - Físicos" },
            new EnumItem { Id = 2132, Descricao = "2132 - Químicos" },
            new EnumItem { Id = 2133, Descricao = "2133 - Profissionais das ciências atmosféricas e espaciais e de astronomia" },
            new EnumItem { Id = 2134, Descricao = "2134 - Geólogos, oceanógrafos, geofísicos e afins" },
            new EnumItem { Id = 2140, Descricao = "2140 - Engenheiros ambientais e afins" },
            new EnumItem { Id = 2141, Descricao = "2141 - Arquitetos e urbanistas" },
            new EnumItem { Id = 2142, Descricao = "2142 - Engenheiros civis e afins" },
            new EnumItem { Id = 2143, Descricao = "2143 - Engenheiros eletricistas, eletrônicos e afins" },
            new EnumItem { Id = 2144, Descricao = "2144 - Engenheiros mecânicos e afins" },
            new EnumItem { Id = 2145, Descricao = "2145 - Engenheiros químicos e afins" },
            new EnumItem { Id = 2146, Descricao = "2146 - Engenheiros metalurgistas, de materiais e afins" },
            new EnumItem { Id = 2147, Descricao = "2147 - Engenheiros de minas e afins" },
            new EnumItem { Id = 2148, Descricao = "2148 - Engenheiros agrimensores e engenheiros cartógrafos" },
            new EnumItem { Id = 2149, Descricao = "2149 - Profissionais de produção, qualidade, saúde, segurança e afins" },
            new EnumItem { Id = 2151, Descricao = "2151 - Oficiais de convés e afins" },
            new EnumItem { Id = 2152, Descricao = "2152 - Oficiais de máquinas da marinha mercante" },
            new EnumItem { Id = 2153, Descricao = "2153 - Profissionais da pilotagem aeronáutica" },
            new EnumItem { Id = 2211, Descricao = "2211 - Biólogos e afins" },
            new EnumItem { Id = 2212, Descricao = "2212 - Biomédicos" },
            new EnumItem { Id = 2221, Descricao = "2221 - Engenheiros agrossilvipecuários" },
            new EnumItem { Id = 2222, Descricao = "2222 - Engenheiros de alimentos e afins" },
            new EnumItem { Id = 2232, Descricao = "2232 - Cirurgiões-dentistas" },
            new EnumItem { Id = 2233, Descricao = "2233 - Veterinários e zootecnistas" },
            new EnumItem { Id = 2234, Descricao = "2234 - Farmacêuticos" },
            new EnumItem { Id = 2235, Descricao = "2235 - Enfermeiros e afins" },
            new EnumItem { Id = 2236, Descricao = "2236 - Fisioterapeutas" },
            new EnumItem { Id = 2237, Descricao = "2237 - Nutricionistas" },
            new EnumItem { Id = 2238, Descricao = "2238 - Fonoaudiólogos" },
            new EnumItem { Id = 2239, Descricao = "2239 - Terapeutas ocupacionais, ortoptistas e psicomotricistas" },
            new EnumItem { Id = 2241, Descricao = "2241 - Profissionais da educação física" },
            new EnumItem { Id = 2251, Descricao = "2251 - Médicos clínicos" },
            new EnumItem { Id = 2252, Descricao = "2252 - Médicos em especialidades cirúrgicas" },
            new EnumItem { Id = 2253, Descricao = "2253 - Médicos em medicina diagnóstica e terapêutica" },
            new EnumItem { Id = 2261, Descricao = "2261 - Osteopatas e quiropraxistas" },
            new EnumItem { Id = 2263, Descricao = "2263 - Profissionais das terapias criativas,equoterápicas e naturológicas" },
            new EnumItem { Id = 2311, Descricao = "2311 - Professores de nível superior na educação infantil" },
            new EnumItem { Id = 2312, Descricao = "2312 - Professores de nível superior do ensino fundamental (primeira a quarta séries)" },
            new EnumItem { Id = 2313, Descricao = "2313 - Professores de nível superior no ensino fundamental de quinta a oitava série" },
            new EnumItem { Id = 2321, Descricao = "2321 - Professores do ensino médio" },
            new EnumItem { Id = 2331, Descricao = "2331 - Professores do ensino profissional" },
            new EnumItem { Id = 2332, Descricao = "2332 - Instrutores de ensino profissional" },
            new EnumItem { Id = 2341, Descricao = "2341 - Professores de matemática, estatística e informática do ensino superior" },
            new EnumItem { Id = 2342, Descricao = "2342 - Professores de ciências físicas, químicas e afins do ensino superior" },
            new EnumItem { Id = 2343, Descricao = "2343 - Professores de arquitetura e urbanismo, engenharia, geofísica e geologia do ensino superior" },
            new EnumItem { Id = 2344, Descricao = "2344 - Professores de ciências biológicas e da saúde do ensino superior" },
            new EnumItem { Id = 2345, Descricao = "2345 - Professores na área de formação pedagógica do ensino superior" },
            new EnumItem { Id = 2346, Descricao = "2346 - Professores nas áreas de língua e literatura do ensino superior" },
            new EnumItem { Id = 2347, Descricao = "2347 - Professores de ciências humanas do ensino superior" },
            new EnumItem { Id = 2348, Descricao = "2348 - Professores de ciências econômicas, administrativas e contábeis do ensino superior" },
            new EnumItem { Id = 2349, Descricao = "2349 - Professores de artes do ensino superior" },
            new EnumItem { Id = 2392, Descricao = "2392 - Professores de educação especial" },
            new EnumItem { Id = 2394, Descricao = "2394 - Programadores, avaliadores e orientadores de ensino" },
            new EnumItem { Id = 2410, Descricao = "2410 - Advogados" },
            new EnumItem { Id = 2412, Descricao = "2412 - Procuradores e advogados públicos" },
            new EnumItem { Id = 2413, Descricao = "2413 - Tabeliães e registradores" },
            new EnumItem { Id = 2414, Descricao = "2414 - Conselheiros julgadores" },
            new EnumItem { Id = 2422, Descricao = "2422 - Membros do ministério público" },
            new EnumItem { Id = 2423, Descricao = "2423 - Delegados de polícia" },
            new EnumItem { Id = 2424, Descricao = "2424 - Defensores públicos e procuradores da assistência judiciária" },
            new EnumItem { Id = 2429, Descricao = "2429 - Profissionais da inteligência" },
            new EnumItem { Id = 2511, Descricao = "2511 - Profissionais em pesquisa e análise antropológica sociológica" },
            new EnumItem { Id = 2512, Descricao = "2512 - Economistas" },
            new EnumItem { Id = 2513, Descricao = "2513 - Profissionais em pesquisa e análise geográfica" },
            new EnumItem { Id = 2514, Descricao = "2514 - Filósofos" },
            new EnumItem { Id = 2515, Descricao = "2515 - Psicólogos e psicanalistas" },
            new EnumItem { Id = 2516, Descricao = "2516 - Assistentes sociais e economistas domésticos" },
            new EnumItem { Id = 2521, Descricao = "2521 - Administradores" },
            new EnumItem { Id = 2522, Descricao = "2522 - Contadores e afins" },
            new EnumItem { Id = 2523, Descricao = "2523 - Secretárias(os) executivas(os) e afins" },
            new EnumItem { Id = 2524, Descricao = "2524 - Profissionais de recursos humanos" },
            new EnumItem { Id = 2525, Descricao = "2525 - Profissionais de administração ecônomico-financeira" },
            new EnumItem { Id = 2526, Descricao = "2526 - Profissionais da administração dos serviços de segurança" },
            new EnumItem { Id = 2527, Descricao = "2527 - Profissionais de planejamento, programação e controles logisticos" },
            new EnumItem { Id = 2531, Descricao = "2531 - Profissionais de publicidade" },
            new EnumItem { Id = 2532, Descricao = "2532 - Profissionais de comercializacão e consultoria de serviços bancários" },
            new EnumItem { Id = 2533, Descricao = "2533 - Corretores de valores, ativos financeiros, mercadorias e derivativos" },
            new EnumItem { Id = 2534, Descricao = "2534 - Profissionais de mídias digitais e afins" },
            new EnumItem { Id = 2541, Descricao = "2541 - Auditores fiscais e técnicos da receita federal" },
            new EnumItem { Id = 2542, Descricao = "2542 - Auditores fiscais da previdência social" },
            new EnumItem { Id = 2543, Descricao = "2543 - Auditores fiscais do trabalho" },
            new EnumItem { Id = 2544, Descricao = "2544 - Fiscais de tributos estaduais e municipais" },
            new EnumItem { Id = 2545, Descricao = "2545 - Profissionais da fiscalização de atividades urbanas" },
            new EnumItem { Id = 2611, Descricao = "2611 - Profissionais do jornalismo" },
            new EnumItem { Id = 2612, Descricao = "2612 - Profissionais da informação" },
            new EnumItem { Id = 2613, Descricao = "2613 - Arquivistas e museólogos" },
            new EnumItem { Id = 2614, Descricao = "2614 - Filólogos,tradutores ,intérpretes e afins" },
            new EnumItem { Id = 2615, Descricao = "2615 - Profissionais da escrita" },
            new EnumItem { Id = 2616, Descricao = "2616 - Editores" },
            new EnumItem { Id = 2617, Descricao = "2617 - Locutores, comentaristas e repórteres de mídias audiovisuais" },
            new EnumItem { Id = 2618, Descricao = "2618 - Fotógrafos profissionais" },
            new EnumItem { Id = 2619, Descricao = "2619 - Assistentes de direção (tv) e continuístas" },
            new EnumItem { Id = 2621, Descricao = "2621 - Produtores artísticos e culturais" },
            new EnumItem { Id = 2622, Descricao = "2622 - Diretores artísticos, de espetáculos e afins" },
            new EnumItem { Id = 2623, Descricao = "2623 - Cenógrafos" },
            new EnumItem { Id = 2624, Descricao = "2624 - Artistas visuais,desenhistas industriais e conservadores-restauradores de bens culturais" },
            new EnumItem { Id = 2625, Descricao = "2625 - Atores" },
            new EnumItem { Id = 2626, Descricao = "2626 - Músicos compositores, arranjadores, regentes e musicólogos" },
            new EnumItem { Id = 2627, Descricao = "2627 - Músicos intérpretes" },
            new EnumItem { Id = 2628, Descricao = "2628 - Artistas da dança (exceto dança tradicional e popular)" },
            new EnumItem { Id = 2629, Descricao = "2629 - Designer de interiores de nível superior" },
            new EnumItem { Id = 2631, Descricao = "2631 - Ministros de culto, missionários, teólogos e profissionais assemelhados" },
            new EnumItem { Id = 2711, Descricao = "2711 - Chefes de cozinha e afins" },
            new EnumItem { Id = 3001, Descricao = "3001 - Técnicos em mecatrônica" },
            new EnumItem { Id = 3003, Descricao = "3003 - Técnicos em eletromecânica" },
            new EnumItem { Id = 3011, Descricao = "3011 - Técnicos de laboratório industrial" },
            new EnumItem { Id = 3012, Descricao = "3012 - Técnicos de apoio à bioengenharia" },
            new EnumItem { Id = 3111, Descricao = "3111 - Técnicos químicos" },
            new EnumItem { Id = 3112, Descricao = "3112 - Técnicos de produção de indústrias químicas, petroquímicas, refino de petróleo, gás e afins" },
            new EnumItem { Id = 3113, Descricao = "3113 - Técnicos em materiais, produtos cerâmicos e vidros" },
            new EnumItem { Id = 3114, Descricao = "3114 - Técnicos em fabricação de produtos plásticos e de borracha" },
            new EnumItem { Id = 3115, Descricao = "3115 - Técnicos em controle ambiental, utilidades e tratamento de efluentes" },
            new EnumItem { Id = 3116, Descricao = "3116 - Técnicos têxteis" },
            new EnumItem { Id = 3117, Descricao = "3117 - Coloristas" },
            new EnumItem { Id = 3121, Descricao = "3121 - Técnicos em construção civil (edificações)" },
            new EnumItem { Id = 3122, Descricao = "3122 - Técnicos em construção civil (obras de infraestrutura)" },
            new EnumItem { Id = 3123, Descricao = "3123 - Técnicos em geomática" },
            new EnumItem { Id = 3131, Descricao = "3131 - Técnicos em eletricidade e eletrotécnica" },
            new EnumItem { Id = 3132, Descricao = "3132 - Técnicos em eletrônica" },
            new EnumItem { Id = 3133, Descricao = "3133 - Técnicos em telecomunicações" },
            new EnumItem { Id = 3134, Descricao = "3134 - Técnicos em calibração e instrumentação" },
            new EnumItem { Id = 3135, Descricao = "3135 - Técnicos em fotônica" },
            new EnumItem { Id = 3141, Descricao = "3141 - Técnicos mecânicos na fabricação e montagem de máquinas, sistemas e instrumentos" },
            new EnumItem { Id = 3142, Descricao = "3142 - Técnicos mecânicos (ferramentas)" },
            new EnumItem { Id = 3143, Descricao = "3143 - Técnicos em mecânica veicular" },
            new EnumItem { Id = 3144, Descricao = "3144 - Técnicos mecânicos na manutenção de máquinas, sistemas e instrumentos" },
            new EnumItem { Id = 3146, Descricao = "3146 - Técnicos em metalurgia (estruturas metálicas)" },
            new EnumItem { Id = 3147, Descricao = "3147 - Técnicos em siderurgia" },
            new EnumItem { Id = 3148, Descricao = "3148 - Especialistas em inspeções industriais" },
            new EnumItem { Id = 3161, Descricao = "3161 - Técnicos em geologia" },
            new EnumItem { Id = 3163, Descricao = "3163 - Técnicos em mineração" },
            new EnumItem { Id = 3171, Descricao = "3171 - Técnicos de desenvolvimento de sistemas e aplicações" },
            new EnumItem { Id = 3172, Descricao = "3172 - Técnicos de suporte e monitoração ao usuário de tecnologia da informação." },
            new EnumItem { Id = 3180, Descricao = "3180 - Desenhistas técnicos, em geral" },
            new EnumItem { Id = 3181, Descricao = "3181 - Desenhistas técnicos da construção civil e arquitetura" },
            new EnumItem { Id = 3182, Descricao = "3182 - Desenhistas técnicos da mecânica" },
            new EnumItem { Id = 3183, Descricao = "3183 - Desenhistas técnicos em eletricidade, eletrônica, eletromecânica, calefação, ventilação e refrigeração" },
            new EnumItem { Id = 3184, Descricao = "3184 - Desenhistas técnicos de produtos e serviços diversos" },
            new EnumItem { Id = 3185, Descricao = "3185 - Desenhistas projetistas de construção civil e arquitetura" },
            new EnumItem { Id = 3186, Descricao = "3186 - Desenhistas projetistas da mecânica" },
            new EnumItem { Id = 3187, Descricao = "3187 - Desenhistas projetistas de eletricidade e eletrônica" },
            new EnumItem { Id = 3188, Descricao = "3188 - Desenhistas projetistas e modelistas de produtos e serviços diversos" },
            new EnumItem { Id = 3191, Descricao = "3191 - Técnicos do vestuário" },
            new EnumItem { Id = 3192, Descricao = "3192 - Técnicos do mobiliário e afins" },
            new EnumItem { Id = 3201, Descricao = "3201 - Técnicos em biologia" },
            new EnumItem { Id = 3211, Descricao = "3211 - Técnicos agrícolas" },
            new EnumItem { Id = 3212, Descricao = "3212 - Técnicos florestais" },
            new EnumItem { Id = 3213, Descricao = "3213 - Técnicos em aqüicultura" },
            new EnumItem { Id = 3221, Descricao = "3221 - Tecnólogos e técnicos em terapias complementares e estéticas" },
            new EnumItem { Id = 3222, Descricao = "3222 - Técnicos e auxiliares de enfermagem" },
            new EnumItem { Id = 3223, Descricao = "3223 - Técnicos em óptica e optometria" },
            new EnumItem { Id = 3224, Descricao = "3224 - Técnicos de odontologia" },
            new EnumItem { Id = 3225, Descricao = "3225 - Técnicos em próteses ortopédicas" },
            new EnumItem { Id = 3226, Descricao = "3226 - Técnicos de imobilizações ortopédicas" },
            new EnumItem { Id = 3227, Descricao = "3227 - Técnicos e profissionais em práticas integrativas e complementares (pics)" },
            new EnumItem { Id = 3231, Descricao = "3231 - Técnicos em pecuária" },
            new EnumItem { Id = 3241, Descricao = "3241 - Tecnólogos e técnicos em métodos de diagnósticos e terapêutica" },
            new EnumItem { Id = 3242, Descricao = "3242 - Técnicos de laboratórios de saúde e bancos de sangue" },
            new EnumItem { Id = 3250, Descricao = "3250 - Enólogos, perfumistas e aromistas" },
            new EnumItem { Id = 3251, Descricao = "3251 - Técnico em farmácia e em manipulação farmacêutica" },
            new EnumItem { Id = 3252, Descricao = "3252 - Técnicos em produção, conservação e de qualidade de alimentos" },
            new EnumItem { Id = 3253, Descricao = "3253 - Técnicos de apoio à biotecnologia" },
            new EnumItem { Id = 3281, Descricao = "3281 - Técnicos em necrópsia e taxidermistas" },
            new EnumItem { Id = 3311, Descricao = "3311 - Professores de nível médio na educação infantil" },
            new EnumItem { Id = 3312, Descricao = "3312 - Professores de nível médio no ensino fundamental" },
            new EnumItem { Id = 3313, Descricao = "3313 - Professores de nível médio no ensino profissionalizante" },
            new EnumItem { Id = 3321, Descricao = "3321 - Professores leigos no ensino fundamental" },
            new EnumItem { Id = 3322, Descricao = "3322 - Professores práticos no ensino profissionalizante" },
            new EnumItem { Id = 3331, Descricao = "3331 - Instrutores e professores de cursos livres" },
            new EnumItem { Id = 3341, Descricao = "3341 - Inspetores de alunos e afins" },
            new EnumItem { Id = 3411, Descricao = "3411 - Pilotos de aviação comercial, mecânicos de vôo e afins" },
            new EnumItem { Id = 3412, Descricao = "3412 - Técnicos marítimos, fluviários e pescadores de convés" },
            new EnumItem { Id = 3413, Descricao = "3413 - Técnicos marítimos e fluviários de máquinas" },
            new EnumItem { Id = 3421, Descricao = "3421 - Especialistas em logística de transportes" },
            new EnumItem { Id = 3422, Descricao = "3422 - Despachantes aduaneiros" },
            new EnumItem { Id = 3423, Descricao = "3423 - Técnicos em transportes rodoviários" },
            new EnumItem { Id = 3424, Descricao = "3424 - Técnicos em transportes metroferroviários" },
            new EnumItem { Id = 3425, Descricao = "3425 - Técnicos em transportes aéreos" },
            new EnumItem { Id = 3426, Descricao = "3426 - Técnicos em transportes por vias navegáveis e operações portuárias" },
            new EnumItem { Id = 3511, Descricao = "3511 - Técnicos em contabilidade" },
            new EnumItem { Id = 3513, Descricao = "3513 - Técnicos em administração" },
            new EnumItem { Id = 3514, Descricao = "3514 - Serventuários da justiça e afins" },
            new EnumItem { Id = 3515, Descricao = "3515 - Técnicos em secretariado, taquígrafos e estenotipistas" },
            new EnumItem { Id = 3516, Descricao = "3516 - Técnicos em segurança do trabalho" },
            new EnumItem { Id = 3517, Descricao = "3517 - Técnicos de seguros e afins" },
            new EnumItem { Id = 3518, Descricao = "3518 - Agentes de investigação e identificação" },
            new EnumItem { Id = 3519, Descricao = "3519 - Técnicos da inteligência" },
            new EnumItem { Id = 3522, Descricao = "3522 - Agentes da saúde e do meio ambiente" },
            new EnumItem { Id = 3523, Descricao = "3523 - Agentes fiscais metrológicos e de qualidade" },
            new EnumItem { Id = 3524, Descricao = "3524 - Profissionais de direitos autorais e de avaliacão de produtos dos meios de comunicação" },
            new EnumItem { Id = 3532, Descricao = "3532 - Técnicos em operações e serviços bancários" },
            new EnumItem { Id = 3541, Descricao = "3541 - Especialistas em promoção de produtos e vendas" },
            new EnumItem { Id = 3542, Descricao = "3542 - Compradores" },
            new EnumItem { Id = 3543, Descricao = "3543 - Analistas de comércio exterior" },
            new EnumItem { Id = 3544, Descricao = "3544 - Leiloeiros e avaliadores" },
            new EnumItem { Id = 3545, Descricao = "3545 - Corretores de seguros" },
            new EnumItem { Id = 3546, Descricao = "3546 - Corretores de imóveis e de grãos" },
            new EnumItem { Id = 3547, Descricao = "3547 - Representantes comerciais autônomos" },
            new EnumItem { Id = 3548, Descricao = "3548 - Técnicos em serviços de turismo e organização de eventos" },
            new EnumItem { Id = 3711, Descricao = "3711 - Técnicos em biblioteconomia" },
            new EnumItem { Id = 3712, Descricao = "3712 - Técnicos em museologia e afins" },
            new EnumItem { Id = 3713, Descricao = "3713 - Técnicos em artes gráficas" },
            new EnumItem { Id = 3714, Descricao = "3714 - Recreadores, brinquedistas e afins" },
            new EnumItem { Id = 3721, Descricao = "3721 - Captadores de imagens em movimento" },
            new EnumItem { Id = 3722, Descricao = "3722 - Operadores de rede de teleprocessamento e afins" },
            new EnumItem { Id = 3731, Descricao = "3731 - Técnicos de operação de registros sonoro/audiovisuais" },
            new EnumItem { Id = 3732, Descricao = "3732 - Supervisores operacionais e técnicos em mídias audiovisuais" },
            new EnumItem { Id = 3741, Descricao = "3741 - Técnicos em áudio" },
            new EnumItem { Id = 3742, Descricao = "3742 - Técnicos em cenografia" },
            new EnumItem { Id = 3743, Descricao = "3743 - Técnicos em operação de aparelhos de projeção" },
            new EnumItem { Id = 3744, Descricao = "3744 - Técnicos em montagem, edição e finalização de mídia audiovisual" },
            new EnumItem { Id = 3751, Descricao = "3751 - Designers de interiores, de vitrines e visual merchandiser e afins (nível médio)" },
            new EnumItem { Id = 3761, Descricao = "3761 - Dançarinos tradicionais e populares" },
            new EnumItem { Id = 3762, Descricao = "3762 - Artistas de circo (circenses)" },
            new EnumItem { Id = 3763, Descricao = "3763 - Apresentadores de eventos, programas e espetáculos" },
            new EnumItem { Id = 3764, Descricao = "3764 - Modelos" },
            new EnumItem { Id = 3771, Descricao = "3771 - Atletas profissionais" },
            new EnumItem { Id = 3772, Descricao = "3772 - Árbitros desportivos" },
            new EnumItem { Id = 3911, Descricao = "3911 - Planejadores, programadores e controladores de produção e manutenção" },
            new EnumItem { Id = 3912, Descricao = "3912 - Técnicos de controle da produção" },
            new EnumItem { Id = 3951, Descricao = "3951 - Técnicos de apoio em pesquisa e desenvolvimento" },
            new EnumItem { Id = 4101, Descricao = "4101 - Supervisores administrativos" },
            new EnumItem { Id = 4102, Descricao = "4102 - Supervisores de serviços financeiros, de câmbio e de controle" },
            new EnumItem { Id = 4110, Descricao = "4110 - Agentes, assistentes e auxiliares administrativos" },
            new EnumItem { Id = 4121, Descricao = "4121 - Operadores de equipamentos de entrada e transmissão de dados" },
            new EnumItem { Id = 4122, Descricao = "4122 - Contínuos" },
            new EnumItem { Id = 4131, Descricao = "4131 - Auxiliares de contabilidade" },
            new EnumItem { Id = 4132, Descricao = "4132 - Escriturários de serviços bancários" },
            new EnumItem { Id = 4141, Descricao = "4141 - Almoxarifes e armazenistas" },
            new EnumItem { Id = 4142, Descricao = "4142 - Apontadores e conferentes" },
            new EnumItem { Id = 4151, Descricao = "4151 - Auxiliares de serviços de documentação, informação e pesquisa" },
            new EnumItem { Id = 4152, Descricao = "4152 - Trabalhadores nos serviços de classificação e entregas de correspondências, encomendas e publicações" },
            new EnumItem { Id = 4153, Descricao = "4153 - Trabalhadores em registros e informações em saúde" },
            new EnumItem { Id = 4201, Descricao = "4201 - Supervisores de atendimento ao público e de pesquisa" },
            new EnumItem { Id = 4211, Descricao = "4211 - Caixas e bilheteiros (exceto caixa de banco)" },
            new EnumItem { Id = 4212, Descricao = "4212 - Coletadores de apostas e de jogos" },
            new EnumItem { Id = 4213, Descricao = "4213 - Cobradores e afins" },
            new EnumItem { Id = 4221, Descricao = "4221 - Recepcionistas" },
            new EnumItem { Id = 4222, Descricao = "4222 - Operadores de telefonia" },
            new EnumItem { Id = 4223, Descricao = "4223 - Operadores de telemarketing e afins" },
            new EnumItem { Id = 4231, Descricao = "4231 - Despachantes documentalistas e afins" },
            new EnumItem { Id = 4241, Descricao = "4241 - Entrevistadores e recenseadores" },
            new EnumItem { Id = 4242, Descricao = "4242 - Aplicadores de provas e afins" },
            new EnumItem { Id = 5101, Descricao = "5101 - Supervisores dos serviços de transporte, turismo, hotelaria e administração de edifícios" },
            new EnumItem { Id = 5102, Descricao = "5102 - Supervisores de lavanderia" },
            new EnumItem { Id = 5103, Descricao = "5103 - Supervisores dos serviços de proteção, segurança e outros" },
            new EnumItem { Id = 5111, Descricao = "5111 - Trabalhadores de segurança e atendimento aos usuários nos transportes" },
            new EnumItem { Id = 5112, Descricao = "5112 - Fiscais e cobradores dos transportes coletivos" },
            new EnumItem { Id = 5114, Descricao = "5114 - Guias de turismo" },
            new EnumItem { Id = 5115, Descricao = "5115 - Condutores de turismo" },
            new EnumItem { Id = 5121, Descricao = "5121 - Trabalhadores dos serviços domésticos em geral" },
            new EnumItem { Id = 5131, Descricao = "5131 - Mordomos e governantas" },
            new EnumItem { Id = 5132, Descricao = "5132 - Cozinheiros" },
            new EnumItem { Id = 5133, Descricao = "5133 - Camareiros, roupeiros e afins" },
            new EnumItem { Id = 5134, Descricao = "5134 - Trabalhadores no atendimento em estabelecimentos de serviços de alimentação, bebidas e hotelaria" },
            new EnumItem { Id = 5135, Descricao = "5135 - Trabalhadores auxiliares nos serviços de alimentação" },
            new EnumItem { Id = 5136, Descricao = "5136 - Churrasqueiros, pizzaiolos e sushimen" },
            new EnumItem { Id = 5141, Descricao = "5141 - Trabalhadores nos serviços de administração de edifícios" },
            new EnumItem { Id = 5142, Descricao = "5142 - Trabalhadores nos serviços de coleta de resíduos, de limpeza e conservação de áreas públicas" },
            new EnumItem { Id = 5143, Descricao = "5143 - Trabalhadores nos serviços de manutenção de edificações, estruturas e equipamentos industriais" },
            new EnumItem { Id = 5151, Descricao = "5151 - Trabalhadores em serviços de promoção e apoio à saúde" },
            new EnumItem { Id = 5152, Descricao = "5152 - Auxiliares de laboratório da saúde" },
            new EnumItem { Id = 5153, Descricao = "5153 - Trabalhadores de atenção, defesa e proteção as pessoas em situação de vulnerabilidade" },
            new EnumItem { Id = 5161, Descricao = "5161 - Trabalhadores nos serviços de embelezamento" },
            new EnumItem { Id = 5162, Descricao = "5162 - Cuidadores de crianças, jovens, adultos e idosos" },
            new EnumItem { Id = 5163, Descricao = "5163 - Tintureiros, lavadeiros e afins, a máquina" },
            new EnumItem { Id = 5164, Descricao = "5164 - Lavadores e passadores de roupa, a mão" },
            new EnumItem { Id = 5165, Descricao = "5165 - Trabalhadores dos serviços funerários" },
            new EnumItem { Id = 5166, Descricao = "5166 - Trabalhadores auxiliares dos serviços funerários" },
            new EnumItem { Id = 5167, Descricao = "5167 - Astrólogos e numerólogos" },
            new EnumItem { Id = 5168, Descricao = "5168 - Esotéricos e afins" },
            new EnumItem { Id = 5169, Descricao = "5169 - Trabalhadores nos serviços de arte corporal" },
            new EnumItem { Id = 5171, Descricao = "5171 - Bombeiros, salva-vidas e afins" },
            new EnumItem { Id = 5172, Descricao = "5172 - Policiais, guardas-civis municipais e agentes de trânsito" },
            new EnumItem { Id = 5173, Descricao = "5173 - Vigilantes e guardas de segurança" },
            new EnumItem { Id = 5174, Descricao = "5174 - Porteiros, vigias e afins" },
            new EnumItem { Id = 5191, Descricao = "5191 - Motociclistas e ciclistas de entregas rápidas" },
            new EnumItem { Id = 5192, Descricao = "5192 - Trabalhadores da coleta e seleção de material reciclável" },
            new EnumItem { Id = 5193, Descricao = "5193 - Trabalhadores cuidadores de animais domésticos" },
            new EnumItem { Id = 5198, Descricao = "5198 - Profissionais do sexo" },
            new EnumItem { Id = 5199, Descricao = "5199 - Outros trabalhadores dos serviços" },
            new EnumItem { Id = 5201, Descricao = "5201 - Supervisores de vendas e de prestação de serviços" },
            new EnumItem { Id = 5211, Descricao = "5211 - Operadores do comércio em lojas e mercados" },
            new EnumItem { Id = 5231, Descricao = "5231 - Instaladores de produtos e acessórios" },
            new EnumItem { Id = 5241, Descricao = "5241 - Vendedores em domicílio" },
            new EnumItem { Id = 5242, Descricao = "5242 - Vendedores em bancas, quiosques e barracas" },
            new EnumItem { Id = 5243, Descricao = "5243 - Vendedores ambulantes" },
            new EnumItem { Id = 6110, Descricao = "6110 - Produtores agropecuários em geral" },
            new EnumItem { Id = 6120, Descricao = "6120 - Produtores agrícolas polivalentes" },
            new EnumItem { Id = 6121, Descricao = "6121 - Produtores agrícolas na cultura de gramíneas" },
            new EnumItem { Id = 6122, Descricao = "6122 - Produtores agrícolas na cultura de plantas fibrosas" },
            new EnumItem { Id = 6123, Descricao = "6123 - Produtores agrícolas na olericultura" },
            new EnumItem { Id = 6124, Descricao = "6124 - Produtores agrícolas no cultivo de flores e plantas ornamentais" },
            new EnumItem { Id = 6125, Descricao = "6125 - Produtores agrícolas na fruticultura" },
            new EnumItem { Id = 6126, Descricao = "6126 - Produtores agrícolas na cultura de plantas estimulantes" },
            new EnumItem { Id = 6127, Descricao = "6127 - Produtores agrícolas na cultura de plantas oleaginosas" },
            new EnumItem { Id = 6128, Descricao = "6128 - Produtores de especiarias e de plantas aromáticas e medicinais" },
            new EnumItem { Id = 6130, Descricao = "6130 - Produtores em pecuária polivalente" },
            new EnumItem { Id = 6131, Descricao = "6131 - Produtores em pecuária de animais de grande porte" },
            new EnumItem { Id = 6132, Descricao = "6132 - Produtores em pecuária de animais de médio porte" },
            new EnumItem { Id = 6133, Descricao = "6133 - Produtores da avicultura e cunicultura" },
            new EnumItem { Id = 6134, Descricao = "6134 - Produtores de animais e insetos úteis" },
            new EnumItem { Id = 6201, Descricao = "6201 - Supervisores na exploração agropecuária" },
            new EnumItem { Id = 6210, Descricao = "6210 - Trabalhadores agropecuários em geral" },
            new EnumItem { Id = 6220, Descricao = "6220 - Trabalhadores de apoio à agricultura" },
            new EnumItem { Id = 6221, Descricao = "6221 - Trabalhadores agrícolas na cultura de gramíneas" },
            new EnumItem { Id = 6222, Descricao = "6222 - Trabalhadores agrícolas na cultura de plantas fibrosas" },
            new EnumItem { Id = 6223, Descricao = "6223 - Trabalhadores agrícolas na olericultura" },
            new EnumItem { Id = 6224, Descricao = "6224 - Trabalhadores agrícolas no cultivo de flores e plantas ornamentais" },
            new EnumItem { Id = 6225, Descricao = "6225 - Trabalhadores agrícolas na fruticultura" },
            new EnumItem { Id = 6226, Descricao = "6226 - Trabalhadores agrícolas nas culturas de plantas estimulantes" },
            new EnumItem { Id = 6227, Descricao = "6227 - Trabalhadores agrícolas na cultura de plantas oleaginosas" },
            new EnumItem { Id = 6228, Descricao = "6228 - Trabalhadores agrícolas da cultura de especiarias e de plantas aromáticas e medicinais" },
            new EnumItem { Id = 6230, Descricao = "6230 - Tratadores polivalentes de animais" },
            new EnumItem { Id = 6231, Descricao = "6231 - Trabalhadores na pecuária de animais de grande porte" },
            new EnumItem { Id = 6232, Descricao = "6232 - Trabalhadores na pecuária de animais de médio porte" },
            new EnumItem { Id = 6233, Descricao = "6233 - Trabalhadores na avicultura e cunicultura" },
            new EnumItem { Id = 6234, Descricao = "6234 - Trabalhadores na criação de insetos e animais úteis" },
            new EnumItem { Id = 6301, Descricao = "6301 - Supervisores na área florestal e aquicultura" },
            new EnumItem { Id = 6310, Descricao = "6310 - Pescadores polivalentes" },
            new EnumItem { Id = 6311, Descricao = "6311 - Pescadores profissionais artesanais de água doce" },
            new EnumItem { Id = 6312, Descricao = "6312 - Pescadores de água costeira e alto mar" },
            new EnumItem { Id = 6313, Descricao = "6313 - Criadores de animais aquáticos" },
            new EnumItem { Id = 6314, Descricao = "6314 - Trabalhadores de apoio à pesca" },
            new EnumItem { Id = 6320, Descricao = "6320 - Trabalhadores florestais polivalentes" },
            new EnumItem { Id = 6321, Descricao = "6321 - Extrativistas e reflorestadores de espécies produtoras de madeira" },
            new EnumItem { Id = 6322, Descricao = "6322 - Extrativistas florestais de espécies produtoras de gomas e resinas" },
            new EnumItem { Id = 6323, Descricao = "6323 - Extrativistas florestais de espécies produtoras de fibras, ceras e óleos" },
            new EnumItem { Id = 6324, Descricao = "6324 - Extrativistas florestais de espécies produtoras de alimentos silvestres" },
            new EnumItem { Id = 6325, Descricao = "6325 - Extrativistas florestais de espécies produtoras de substâncias aromáticas, medicinais e tóxicas" },
            new EnumItem { Id = 6326, Descricao = "6326 - Carvoejadores" },
            new EnumItem { Id = 6410, Descricao = "6410 - Trabalhadores da mecanização agrícola" },
            new EnumItem { Id = 6420, Descricao = "6420 - Trabalhadores da mecanização florestal" },
            new EnumItem { Id = 6430, Descricao = "6430 - Trabalhadores da irrigação e drenagem" },
            new EnumItem { Id = 7101, Descricao = "7101 - Supervisores da extração mineral" },
            new EnumItem { Id = 7102, Descricao = "7102 - Supervisores da construção civil" },
            new EnumItem { Id = 7111, Descricao = "7111 - Trabalhadores da extração de minerais sólidos" },
            new EnumItem { Id = 7112, Descricao = "7112 - Trabalhadores de extração de minerais sólidos (operadores de máquinas)" },
            new EnumItem { Id = 7113, Descricao = "7113 - Trabalhadores da extração de minerais líquidos e gasosos" },
            new EnumItem { Id = 7114, Descricao = "7114 - Garimpeiros e operadores de salinas" },
            new EnumItem { Id = 7121, Descricao = "7121 - Trabalhadores de beneficiamento de minérios" },
            new EnumItem { Id = 7122, Descricao = "7122 - Trabalhadores de beneficiamento de pedras ornamentais" },
            new EnumItem { Id = 7151, Descricao = "7151 - Trabalhadores na operação de máquinas de terraplenagem e fundações" },
            new EnumItem { Id = 7152, Descricao = "7152 - Trabalhadores de estruturas de alvenaria" },
            new EnumItem { Id = 7153, Descricao = "7153 - Montadores de estruturas de concreto armado" },
            new EnumItem { Id = 7154, Descricao = "7154 - Trabalhadores na operação de máquinas de concreto usinado e afins" },
            new EnumItem { Id = 7155, Descricao = "7155 - Trabalhadores de montagem de estruturas de madeira, metal e compósitos em obras civis" },
            new EnumItem { Id = 7156, Descricao = "7156 - Trabalhadores de instalações elétricas" },
            new EnumItem { Id = 7157, Descricao = "7157 - Aplicadores de materiais isolantes" },
            new EnumItem { Id = 7161, Descricao = "7161 - Revestidores de concreto" },
            new EnumItem { Id = 7162, Descricao = "7162 - Telhadores (revestimentos rígidos)" },
            new EnumItem { Id = 7163, Descricao = "7163 - Vidraceiros (revestimentos rígidos)" },
            new EnumItem { Id = 7164, Descricao = "7164 - Gesseiros" },
            new EnumItem { Id = 7165, Descricao = "7165 - Aplicadores de revestimentos cerâmicos, pastilhas, pedras e madeiras" },
            new EnumItem { Id = 7166, Descricao = "7166 - Pintores de obras e revestidores de interiores (revestimentos flexíveis)" },
            new EnumItem { Id = 7170, Descricao = "7170 - Operadores de equipamentos da construção civil" },
            new EnumItem { Id = 7201, Descricao = "7201 - Supervisores de usinagem, conformação e tratamento de metais" },
            new EnumItem { Id = 7202, Descricao = "7202 - Supervisores da fabricação e montagem metalmecânica" },
            new EnumItem { Id = 7211, Descricao = "7211 - Ferramenteiros e afins" },
            new EnumItem { Id = 7212, Descricao = "7212 - Preparadores e operadores de máquinas-ferramenta convencionais" },
            new EnumItem { Id = 7213, Descricao = "7213 - Afiadores e polidores de metais" },
            new EnumItem { Id = 7214, Descricao = "7214 - Operadores de máquinas de usinagem cnc" },
            new EnumItem { Id = 7221, Descricao = "7221 - Trabalhadores de forjamento de metais" },
            new EnumItem { Id = 7222, Descricao = "7222 - Trabalhadores de fundição de metais puros e de ligas metálicas" },
            new EnumItem { Id = 7223, Descricao = "7223 - Trabalhadores de moldagem de metais e de ligas metálicas" },
            new EnumItem { Id = 7224, Descricao = "7224 - Trabalhadores de trefilação e estiramento de metais puros e ligas metálicas" },
            new EnumItem { Id = 7231, Descricao = "7231 - Trabalhadores de tratamento térmico de metais" },
            new EnumItem { Id = 7232, Descricao = "7232 - Trabalhadores de tratamento de superfícies de metais e de compósitos (termoquímicos)" },
            new EnumItem { Id = 7233, Descricao = "7233 - Trabalhadores da pintura de equipamentos, veículos, estruturas metálicas e de compósitos" },
            new EnumItem { Id = 7241, Descricao = "7241 - Encanadores e instaladores de tubulações" },
            new EnumItem { Id = 7242, Descricao = "7242 - Trabalhadores de traçagem e montagem de estruturas metálicas e de compósitos" },
            new EnumItem { Id = 7243, Descricao = "7243 - Trabalhadores de soldagem e corte de ligas metálicas" },
            new EnumItem { Id = 7244, Descricao = "7244 - Trabalhadores de caldeiraria e serralheria" },
            new EnumItem { Id = 7245, Descricao = "7245 - Operadores de máquinas de conformação de metais" },
            new EnumItem { Id = 7246, Descricao = "7246 - Trançadores e laceiros de cabos de aço" },
            new EnumItem { Id = 7250, Descricao = "7250 - Ajustadores mecânicos polivalentes e afins" },
            new EnumItem { Id = 7251, Descricao = "7251 - Montadores de máquinas, aparelhos e acessórios em linhas de montagem" },
            new EnumItem { Id = 7252, Descricao = "7252 - Montadores de máquinas industriais" },
            new EnumItem { Id = 7253, Descricao = "7253 - Montadores de máquinas pesadas e equipamentos agrícolas" },
            new EnumItem { Id = 7254, Descricao = "7254 - Mecânicos montadores de motores e turboalimentadores" },
            new EnumItem { Id = 7255, Descricao = "7255 - Montadores de veículos automotores (linha de montagem)" },
            new EnumItem { Id = 7256, Descricao = "7256 - Montadores de sistemas e estruturas de aeronaves" },
            new EnumItem { Id = 7257, Descricao = "7257 - Instaladores de equipamentos de refrigeração e ventilação" },
            new EnumItem { Id = 7301, Descricao = "7301 - Supervisores de montagens e instalações eletroeletrônicas" },
            new EnumItem { Id = 7311, Descricao = "7311 - Montadores de equipamentos eletroeletrônicos" },
            new EnumItem { Id = 7312, Descricao = "7312 - Montadores de aparelhos de telecomunicações" },
            new EnumItem { Id = 7313, Descricao = "7313 - Instaladores-reparadores de linhas e equipamentos de telecomunicações" },
            new EnumItem { Id = 7321, Descricao = "7321 - Instaladores e reparadores de linhas e cabos elétricos, telefônicos e de comunicação de dados" },
            new EnumItem { Id = 7401, Descricao = "7401 - Supervisores da mecânica de precisão e instrumentos musicais" },
            new EnumItem { Id = 7411, Descricao = "7411 - Mecânicos de instrumentos de precisão" },
            new EnumItem { Id = 7421, Descricao = "7421 - Confeccionadores de instrumentos musicais" },
            new EnumItem { Id = 7501, Descricao = "7501 - Supervisores de joalheria e afins" },
            new EnumItem { Id = 7502, Descricao = "7502 - Supervisores de vidraria, cerâmica e afins" },
            new EnumItem { Id = 7510, Descricao = "7510 - Joalheiros e lapidadores de gemas" },
            new EnumItem { Id = 7511, Descricao = "7511 - Artesãos de metais preciosos e semipreciosos" },
            new EnumItem { Id = 7521, Descricao = "7521 - Sopradores, moldadores e modeladores de vidros e afins" },
            new EnumItem { Id = 7522, Descricao = "7522 - Trabalhadores da transformação de vidros planos" },
            new EnumItem { Id = 7523, Descricao = "7523 - Ceramistas (preparação e fabricação)" },
            new EnumItem { Id = 7524, Descricao = "7524 - Vidreiros e ceramistas (arte e decoração)" },
            new EnumItem { Id = 7601, Descricao = "7601 - Supervisores da indústria têxtil" },
            new EnumItem { Id = 7602, Descricao = "7602 - Supervisores na indústria do curtimento" },
            new EnumItem { Id = 7603, Descricao = "7603 - Supervisores na confecção do vestuário" },
            new EnumItem { Id = 7604, Descricao = "7604 - Supervisores na confecção de calçados" },
            new EnumItem { Id = 7605, Descricao = "7605 - Supervisores da confecção de artefatos de tecidos, couros e afins" },
            new EnumItem { Id = 7606, Descricao = "7606 - Supervisores das artes gráficas" },
            new EnumItem { Id = 7610, Descricao = "7610 - Trabalhadores polivalentes das indústrias têxteis" },
            new EnumItem { Id = 7611, Descricao = "7611 - Trabalhadores da classificação de fibras têxteis e lavagem de lã" },
            new EnumItem { Id = 7612, Descricao = "7612 - Operadores da fiação" },
            new EnumItem { Id = 7613, Descricao = "7613 - Operadores de tear e máquinas similares" },
            new EnumItem { Id = 7614, Descricao = "7614 - Trabalhadores de acabamento, tingimento e estamparia das indústrias têxteis" },
            new EnumItem { Id = 7618, Descricao = "7618 - Inspetores e revisores de produção têxtil" },
            new EnumItem { Id = 7620, Descricao = "7620 - Trabalhadores polivalentes do curtimento de couros e peles" },
            new EnumItem { Id = 7621, Descricao = "7621 - Trabalhadores da preparação do curtimento de couros e peles" },
            new EnumItem { Id = 7622, Descricao = "7622 - Trabalhadores do curtimento de couros e peles" },
            new EnumItem { Id = 7623, Descricao = "7623 - Trabalhadores do acabamento de couros e peles" },
            new EnumItem { Id = 7630, Descricao = "7630 - Profissionais polivalentes da confecção de roupas" },
            new EnumItem { Id = 7631, Descricao = "7631 - Trabalhadores da preparação da confecção de roupas" },
            new EnumItem { Id = 7632, Descricao = "7632 - Operadores de máquinas para costura de peças do vestuário" },
            new EnumItem { Id = 7633, Descricao = "7633 - Operadores de máquinas para bordado e acabamento de roupas" },
            new EnumItem { Id = 7640, Descricao = "7640 - Trabalhadores polivalentes da confecção de calçados" },
            new EnumItem { Id = 7641, Descricao = "7641 - Trabalhadores da preparação da confecção de calçados" },
            new EnumItem { Id = 7642, Descricao = "7642 - Operadores de máquinas de costurar e montar calçados" },
            new EnumItem { Id = 7643, Descricao = "7643 - Trabalhadores de acabamento de calçados" },
            new EnumItem { Id = 7650, Descricao = "7650 - Trabalhadores polivalentes da confecção de artefatos de tecidos e couros" },
            new EnumItem { Id = 7651, Descricao = "7651 - Trabalhadores da preparação de artefatos de tecidos, couros e tapeçaria" },
            new EnumItem { Id = 7652, Descricao = "7652 - Trabalhadores da confecção de artefatos de tecidos, couros e sintéticos" },
            new EnumItem { Id = 7653, Descricao = "7653 - Operadores de máquinas na confecção de artefatos de couro" },
            new EnumItem { Id = 7654, Descricao = "7654 - Trabalhadores do acabamento de artefatos de tecidos e couros" },
            new EnumItem { Id = 7661, Descricao = "7661 - Trabalhadores da pré-impressão gráfica" },
            new EnumItem { Id = 7662, Descricao = "7662 - Trabalhadores da impressão gráfica" },
            new EnumItem { Id = 7663, Descricao = "7663 - Trabalhadores do acabamento gráfico" },
            new EnumItem { Id = 7664, Descricao = "7664 - Trabalhadores de laboratório fotográfico e radiológico" },
            new EnumItem { Id = 7681, Descricao = "7681 - Trabalhadores de tecelagem manual, tricô, crochê, rendas e afins" },
            new EnumItem { Id = 7682, Descricao = "7682 - Trabalhadores artesanais da confecção de peças e tecidos" },
            new EnumItem { Id = 7683, Descricao = "7683 - Trabalhadores artesanais da confecção de calçados e artefatos de couros e peles" },
            new EnumItem { Id = 7686, Descricao = "7686 - Trabalhadores tipográficos linotipistas e afins" },
            new EnumItem { Id = 7687, Descricao = "7687 - Encadernadores e recuperadores de livros (pequenos lotes ou a unidade)" },
            new EnumItem { Id = 7701, Descricao = "7701 - Supervisores em indústria de madeira, mobiliário e da carpintaria veicular" },
            new EnumItem { Id = 7711, Descricao = "7711 - Marceneiros e afins" },
            new EnumItem { Id = 7721, Descricao = "7721 - Trabalhadores de tratamento e preparação da madeira" },
            new EnumItem { Id = 7731, Descricao = "7731 - Operadores de máquinas de desdobramento da madeira" },
            new EnumItem { Id = 7732, Descricao = "7732 - Operadores de máquinas de aglomeração e prensagem de chapas" },
            new EnumItem { Id = 7733, Descricao = "7733 - Operadores de usinagem convencional de madeira" },
            new EnumItem { Id = 7734, Descricao = "7734 - Operadores de máquina de usinar madeira (produção em série)" },
            new EnumItem { Id = 7735, Descricao = "7735 - Operadores de máquinas de usinagem de madeira cnc" },
            new EnumItem { Id = 7741, Descricao = "7741 - Montadores de móveis e artefatos de madeira" },
            new EnumItem { Id = 7751, Descricao = "7751 - Trabalhadores de arte e do acabamento em madeira do mobiliário" },
            new EnumItem { Id = 7764, Descricao = "7764 - Confeccionadores de artefatos de madeira, móveis de vime e afins" },
            new EnumItem { Id = 7771, Descricao = "7771 - Carpinteiros navais" },
            new EnumItem { Id = 7772, Descricao = "7772 - Carpinteiros de carrocerias e carretas" },
            new EnumItem { Id = 7801, Descricao = "7801 - Supervisores de trabalhadores de embalagem e etiquetagem" },
            new EnumItem { Id = 7811, Descricao = "7811 - Condutores de processos robotizados" },
            new EnumItem { Id = 7813, Descricao = "7813 - Operadores de equipamentos pilotados remotamente" },
            new EnumItem { Id = 7817, Descricao = "7817 - Trabalhadores subaquáticos" },
            new EnumItem { Id = 7821, Descricao = "7821 - Operadores de máquinas e equipamentos de elevação" },
            new EnumItem { Id = 7822, Descricao = "7822 - Operadores de equipamentos de movimentação de cargas" },
            new EnumItem { Id = 7823, Descricao = "7823 - Motoristas de veículos de pequeno e médio porte" },
            new EnumItem { Id = 7824, Descricao = "7824 - Condutores de ônibus urbanos, metropolitanos e rodoviários" },
            new EnumItem { Id = 7825, Descricao = "7825 - Motoristas de veículos de cargas em geral" },
            new EnumItem { Id = 7826, Descricao = "7826 - Operadores de veículos sobre trilhos e cabos aéreos" },
            new EnumItem { Id = 7827, Descricao = "7827 - Trabalhadores aquaviários" },
            new EnumItem { Id = 7828, Descricao = "7828 - Condutores de animais e de veículos de tração animal e pedais" },
            new EnumItem { Id = 7831, Descricao = "7831 - Trabalhadores de manobras de transportes sobre trilhos" },
            new EnumItem { Id = 7832, Descricao = "7832 - Trabalhadores de cargas e descargas de mercadorias" },
            new EnumItem { Id = 7841, Descricao = "7841 - Trabalhadores de embalagem e de etiquetagem" },
            new EnumItem { Id = 7842, Descricao = "7842 - Alimentadores de linhas de produção" },
            new EnumItem { Id = 7911, Descricao = "7911 - Artesãos" },
            new EnumItem { Id = 8101, Descricao = "8101 - Supervisores de produção em indústrias químicas, petroquímicas e afins" },
            new EnumItem { Id = 8102, Descricao = "8102 - Supervisores de produção em indústrias de transformação de plásticos e borrachas" },
            new EnumItem { Id = 8103, Descricao = "8103 - Supervisores de produção em indústrias de produtos farmacêuticos, cosméticos e afins" },
            new EnumItem { Id = 8110, Descricao = "8110 - Operadores polivalentes de equipamentos em indústrias químicas, petroquímicas e afins" },
            new EnumItem { Id = 8111, Descricao = "8111 - Operadores de equipamentos de moagem e mistura de materiais (tratamentos químicos e afins)" },
            new EnumItem { Id = 8112, Descricao = "8112 - Operadores de calcinação e de tratamentos químicos de materiais radioativos" },
            new EnumItem { Id = 8113, Descricao = "8113 - Operadores de equipamentos de filtragem e separação" },
            new EnumItem { Id = 8114, Descricao = "8114 - Operadores de equipamentos de destilação, evaporação e reação" },
            new EnumItem { Id = 8115, Descricao = "8115 - Operadores de equipamentos de produção e refino de petróleo e gás" },
            new EnumItem { Id = 8116, Descricao = "8116 - Operadores de equipamentos de coqueificação" },
            new EnumItem { Id = 8117, Descricao = "8117 - Operadores de instalações e máquinas de produtos plásticos, de borracha e moldadores de parafinas" },
            new EnumItem { Id = 8118, Descricao = "8118 - Operadores de máquinas e instalações de produtos farmacêuticos, cosméticos e afins" },
            new EnumItem { Id = 8121, Descricao = "8121 - Trabalhadores da fabricação de munição e explosivos químicos" },
            new EnumItem { Id = 8131, Descricao = "8131 - Operadores de processos das indústrias de transformação de produtos químicos, petroquímicos e afins" },
            new EnumItem { Id = 8181, Descricao = "8181 - Laboratoristas industriais auxiliares" },
            new EnumItem { Id = 8201, Descricao = "8201 - Supervisores de produção em indústrias siderúrgicas" },
            new EnumItem { Id = 8202, Descricao = "8202 - Supervisores na fabricação de materiais para construção (vidros e cerâmicas)" },
            new EnumItem { Id = 8211, Descricao = "8211 - Operadores de instalações de sinterização" },
            new EnumItem { Id = 8212, Descricao = "8212 - Operadores de fornos de primeira fusão e aciaria" },
            new EnumItem { Id = 8213, Descricao = "8213 - Operadores de equipamentos de laminação" },
            new EnumItem { Id = 8214, Descricao = "8214 - Operadores de equipamentos de acabamento de chapas e metais" },
            new EnumItem { Id = 8221, Descricao = "8221 - Forneiros metalúrgicos (segunda fusão e reaquecimento)" },
            new EnumItem { Id = 8231, Descricao = "8231 - Operadores na preparação de massas para abrasivo, vidro, cerâmica, porcelana e materiais de construção" },
            new EnumItem { Id = 8232, Descricao = "8232 - Operadores de equipamentos de fabricação e beneficiamento de cristais, vidros, cerâmicas, porcelanas, fibras de vidro, abrasivos e afins" },
            new EnumItem { Id = 8233, Descricao = "8233 - Operadores de instalações e equipamentos de fabricação de materiais de construção" },
            new EnumItem { Id = 8281, Descricao = "8281 - Trabalhadores da fabricação de cerâmica estrutural para construção" },
            new EnumItem { Id = 8301, Descricao = "8301 - Supervisores da fabricação de celulose e papel" },
            new EnumItem { Id = 8311, Descricao = "8311 - Preparadores de pasta para fabricação de papel" },
            new EnumItem { Id = 8321, Descricao = "8321 - Operadores de máquinas de fabricar papel e papelão" },
            new EnumItem { Id = 8331, Descricao = "8331 - Operadores de máquinas na fabricação de produtos de papel e papelão" },
            new EnumItem { Id = 8332, Descricao = "8332 - Trabalhadores artesanais de produtos de papel e papelão" },
            new EnumItem { Id = 8401, Descricao = "8401 - Supervisores da fabricação de alimentos, bebidas e fumo" },
            new EnumItem { Id = 8411, Descricao = "8411 - Trabalhadores da indústria de beneficiamento de grãos, cereais e afins" },
            new EnumItem { Id = 8412, Descricao = "8412 - Trabalhadores no beneficiamento do sal" },
            new EnumItem { Id = 8413, Descricao = "8413 - Trabalhadores na fabricação e refino de açúcar" },
            new EnumItem { Id = 8414, Descricao = "8414 - Trabalhadores na fabricação e conservação de alimentos" },
            new EnumItem { Id = 8415, Descricao = "8415 - Trabalhadores na pasteurização do leite e na fabricação de laticínios e afins" },
            new EnumItem { Id = 8416, Descricao = "8416 - Trabalhadores na industrialização de café, cacau, mate e de produtos afins" },
            new EnumItem { Id = 8417, Descricao = "8417 - Trabalhadores na fabricação de cachaça, cerveja, vinhos e outras bebidas" },
            new EnumItem { Id = 8418, Descricao = "8418 - Operadores de equipamentos na fabricação de pães, massas alimentícias, doces, chocolates e achocolatados" },
            new EnumItem { Id = 8421, Descricao = "8421 - Cigarreiros e beneficiadores de fumo" },
            new EnumItem { Id = 8422, Descricao = "8422 - Charuteiros" },
            new EnumItem { Id = 8423, Descricao = "8423 - Cigarreiros" },
            new EnumItem { Id = 8481, Descricao = "8481 - Trabalhadores artesanais na conservação de alimentos" },
            new EnumItem { Id = 8482, Descricao = "8482 - Trabalhadores artesanais na pasteurização do leite e na fabricação de laticínios e afins" },
            new EnumItem { Id = 8483, Descricao = "8483 - Padeiros, confeiteiros e afins" },
            new EnumItem { Id = 8484, Descricao = "8484 - Trabalhadores na degustação e classificação de grãos e afins" },
            new EnumItem { Id = 8485, Descricao = "8485 - Magarefes e afins" },
            new EnumItem { Id = 8486, Descricao = "8486 - Trabalhadores artesanais na indústria do fumo" },
            new EnumItem { Id = 8601, Descricao = "8601 - Supervisores da produção de utilidades" },
            new EnumItem { Id = 8611, Descricao = "8611 - Operadores de instalações de geração e distribuição de energia elétrica, hidráulica, térmica ou nuclear" },
            new EnumItem { Id = 8612, Descricao = "8612 - Operadores de instalações de distribuição de energia elétrica" },
            new EnumItem { Id = 8621, Descricao = "8621 - Operadores de máquinas a vapor e utilidades" },
            new EnumItem { Id = 8622, Descricao = "8622 - Operadores de instalações de captação, tratamento e distribuição de água" },
            new EnumItem { Id = 8623, Descricao = "8623 - Operadores de instalações de captação e esgotos" },
            new EnumItem { Id = 8624, Descricao = "8624 - Operadores de instalações de extração, processamento, envasamento e distribuição de gases" },
            new EnumItem { Id = 8625, Descricao = "8625 - Operadores de instalações de refrigeração e ar-condicionado" },
            new EnumItem { Id = 9101, Descricao = "9101 - Supervisores em serviços de reparação e manutenção de máquinas e equipamentos industriais, comerciais e residenciais" },
            new EnumItem { Id = 9102, Descricao = "9102 - Supervisores em serviços de reparação e manutenção veicular" },
            new EnumItem { Id = 9109, Descricao = "9109 - Supervisores de outros trabalhadores de serviços de reparação, conservação e manutenção" },
            new EnumItem { Id = 9111, Descricao = "9111 - Mecânicos de manutenção de bombas, motores, compressores e equipamentos de transmissão" },
            new EnumItem { Id = 9112, Descricao = "9112 - Mecânicos de manutenção e instalação de aparelhos de climatização e refrigeração" },
            new EnumItem { Id = 9113, Descricao = "9113 - Mecânicos de manutenção de máquinas industriais" },
            new EnumItem { Id = 9131, Descricao = "9131 - Mecânicos de manutenção de máquinas pesadas e equipamentos agrícolas" },
            new EnumItem { Id = 9141, Descricao = "9141 - Mecânicos de manutenção aeronáutica" },
            new EnumItem { Id = 9142, Descricao = "9142 - Mecânicos de manutenção de motores e equipamentos navais" },
            new EnumItem { Id = 9143, Descricao = "9143 - Mecânicos de manutenção metroferroviária" },
            new EnumItem { Id = 9144, Descricao = "9144 - Mecânicos de manutenção de veículos automotores" },
            new EnumItem { Id = 9151, Descricao = "9151 - Técnicos em manutenção e reparação de instrumentos de medição e precisão" },
            new EnumItem { Id = 9152, Descricao = "9152 - Restauradores de instrumentos musicais" },
            new EnumItem { Id = 9153, Descricao = "9153 - Técnicos em manutenção e reparação de equipamentos biomédicos" },
            new EnumItem { Id = 9154, Descricao = "9154 - Reparadores de equipamentos fotográficos" },
            new EnumItem { Id = 9191, Descricao = "9191 - Lubrificadores" },
            new EnumItem { Id = 9192, Descricao = "9192 - Trabalhadores de manutenção de roçadeiras, motoserras e similares" },
            new EnumItem { Id = 9193, Descricao = "9193 - Mecânicos de manutenção de bicicletas e equipamentos esportivos e de ginástica" },
            new EnumItem { Id = 9501, Descricao = "9501 - Supervisores de manutenção eletroeletrônica industrial, comercial e predial" },
            new EnumItem { Id = 9502, Descricao = "9502 - Supervisores de manutenção eletroeletrônica veicular" },
            new EnumItem { Id = 9503, Descricao = "9503 - Supervisores de manutenção eletromecânica" },
            new EnumItem { Id = 9511, Descricao = "9511 - Eletricistas de manutenção eletroeletrônica" },
            new EnumItem { Id = 9513, Descricao = "9513 - Instaladores e mantenedores de sistemas eletroeletrônicos de segurança" },
            new EnumItem { Id = 9531, Descricao = "9531 - Eletricistas eletrônicos de manutenção veicular (aérea, terrestre e naval)" },
            new EnumItem { Id = 9541, Descricao = "9541 - Instaladores e mantenedores eletromecânicos de elevadores, escadas e portas automáticas" },
            new EnumItem { Id = 9542, Descricao = "9542 - Reparadores de aparelhos eletrodomésticos" },
            new EnumItem { Id = 9543, Descricao = "9543 - Reparadores de equipamentos de escritório" },
            new EnumItem { Id = 9911, Descricao = "9911 - Conservadores de vias permanentes (trilhos)" },
            new EnumItem { Id = 9912, Descricao = "9912 - Mantenedores de equipamentos de parques de diversões e similares" },
            new EnumItem { Id = 9913, Descricao = "9913 - Reparadores de carrocerias de veículos" },
            new EnumItem { Id = 9914, Descricao = "9914 - Mantenedores de edificações" },
            new EnumItem { Id = 9921, Descricao = "9921 - Trabalhadores elementares de serviços de manutenção veicular" },
            new EnumItem { Id = 9922, Descricao = "9922 - Trabalhadores operacionais de conservação de vias permanentes (exceto trilhos)" }
        ];
    }
}