using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Master.Entity.Const
{
    [ExcludeFromCodeCoverage]
    public static class PrequalCbo3D
    {
        public static readonly List<EnumItem> Vector =
        [
            new EnumItem { Id = 10, Descricao = "010 - MEMBROS DAS FORÇAS ARMADAS" },
            new EnumItem { Id = 20, Descricao = "020 - OFICIAIS DE POLÍCIA MILITAR" },
            new EnumItem { Id = 21, Descricao = "021 - PRAÇAS DE POLÍCIA MILITAR" },
            new EnumItem { Id = 30, Descricao = "030 - OFICIAIS DE BOMBEIRO MILITAR" },
            new EnumItem { Id = 31, Descricao = "031 - PRAÇAS DE BOMBEIRO MILITAR" },
            new EnumItem { Id = 111, Descricao = "111 - MEMBROS SUPERIORES DO PODER LEGISLATIVO, EXECUTIVO E JUDICIÁRIO" },
            new EnumItem { Id = 113, Descricao = "113 - CHEFES DE PEQUENAS POPULAÇÕES" },
            new EnumItem { Id = 114, Descricao = "114 - DIRIGENTES E ADMINISTRADORES DE ORGANIZAÇÃO DE INTERESSE PÚBLICO" },
            new EnumItem { Id = 121, Descricao = "121 - DIRETORES GERAIS" },
            new EnumItem { Id = 122, Descricao = "122 - DIRETORES DE PRODUÇÃO E OPERAÇÕES" },
            new EnumItem { Id = 123, Descricao = "123 - DIRETORES DE ÁREAS DE APOIO" },
            new EnumItem { Id = 131, Descricao = "131 - DIRETORES E GERENTES EM EMPRESA DE SERVIÇOS DE SAÚDE, DE EDUCAÇÃO, OU DE SERVIÇOS CULTURAIS, SOCIAIS OU PESSOAIS" },
            new EnumItem { Id = 141, Descricao = "141 - GERENTES DE PRODUÇÃO E OPERAÇÕES" },
            new EnumItem { Id = 142, Descricao = "142 - GERENTES DE ÁREAS DE APOIO" },
            new EnumItem { Id = 201, Descricao = "201 - PROFISSIONAIS DA BIOTECNOLOGIA E METROLOGIA" },
            new EnumItem { Id = 202, Descricao = "202 - PROFISSIONAIS DA ELETROMECÂNICA" },
            new EnumItem { Id = 203, Descricao = "203 - PESQUISADORES" },
            new EnumItem { Id = 204, Descricao = "204 - PROFISSIONAIS DE INVESTIGAÇÃO CRIMINAL" },
            new EnumItem { Id = 211, Descricao = "211 - MATEMÁTICOS, ESTATÍSTICOS E AFINS" },
            new EnumItem { Id = 212, Descricao = "212 - PROFISSIONAIS DA INFORMÁTICA" },
            new EnumItem { Id = 213, Descricao = "213 - FÍSICOS, QUÍMICOS E AFINS" },
            new EnumItem { Id = 214, Descricao = "214 - ENGENHEIROS, ARQUITETOS E AFINS" },
            new EnumItem { Id = 215, Descricao = "215 - PROFISSIONAIS EM NAVEGAÇÃO AÉREA, MARÍTIMA E FLUVIAL" },
            new EnumItem { Id = 221, Descricao = "221 - BIÓLOGOS E AFINS" },
            new EnumItem { Id = 222, Descricao = "222 - AGRÔNOMOS E AFINS" },
            new EnumItem { Id = 223, Descricao = "223 - PROFISSIONAIS DA MEDICINA, SAÚDE E AFINS" },
            new EnumItem { Id = 224, Descricao = "224 - PROFISSIONAIS DA EDUCAÇÃO FÍSICA" },
            new EnumItem { Id = 225, Descricao = "225 - PROFISSIONAIS DA MEDICINA" },
            new EnumItem { Id = 226, Descricao = "226 - PROFISSIONAIS DE SAÚDE EM PRATICAS INTEGRATIVAS E COMPLEMENTARES" },
            new EnumItem { Id = 231, Descricao = "231 - PROFESSORES DE NÍVEL SUPERIOR NA EDUCAÇÃO INFANTIL E NO ENSINO FUNDAMENTAL" },
            new EnumItem { Id = 232, Descricao = "232 - PROFESSORES DO ENSINO MÉDIO" },
            new EnumItem { Id = 233, Descricao = "233 - PROFESSORES E INSTRUTORES DO ENSINO PROFISSIONAL" },
            new EnumItem { Id = 234, Descricao = "234 - PROFESSORES DO ENSINO SUPERIOR" },
            new EnumItem { Id = 239, Descricao = "239 - OUTROS PROFISSIONAIS DO ENSINO NÃO CLASSIFICADOS ANTERIORMENTE" },
            new EnumItem { Id = 241, Descricao = "241 - ADVOGADOS, PROCURADORES, TABELIÃES E AFINS" },
            new EnumItem { Id = 242, Descricao = "242 - ADVOGADOS DO PODER JUDICIÁRIO E DA SEGURANÇA PÚBLICA" },
            new EnumItem { Id = 251, Descricao = "251 - CIENTISTAS SOCIAIS, PSICÓLOGOS E AFINS" },
            new EnumItem { Id = 252, Descricao = "252 - PROFISSIONAIS DE ORGANIZAÇÃO E ADMINISTRAÇÃO DE EMPRESAS E AFINS" },
            new EnumItem { Id = 253, Descricao = "253 - PROFISSIONAIS DE RELAÇÕES PÚBLICAS, PUBLICIDADE, MARKETING E COMERCIALIZAÇÃO" },
            new EnumItem { Id = 254, Descricao = "254 - AUDITORES FISCAIS PÚBLICOS" },
            new EnumItem { Id = 261, Descricao = "261 - PROFISSIONAIS DA COMUNICAÇÃO E DA INFORMAÇÃO" },
            new EnumItem { Id = 262, Descricao = "262 - PROFISSIONAIS DE ESPETÁCULOS E DAS ARTES" },
            new EnumItem { Id = 263, Descricao = "263 - MEMBROS DE CULTOS RELIGIOSOS E AFINS" },
            new EnumItem { Id = 271, Descricao = "271 - PROFISSIONAIS EM GASTRONOMIA E SERVIÇOS DE ALIMENTAÇÃO" },
            new EnumItem { Id = 300, Descricao = "300 - TÉCNICOS MECATRÔNICOS E ELETROMECÂNICOS" },
            new EnumItem { Id = 301, Descricao = "301 - TÉCNICOS EM LABORATÓRIO" },
            new EnumItem { Id = 311, Descricao = "311 - TÉCNICO EM CIÊNCIAS FÍSICAS E QUÍMICAS" },
            new EnumItem { Id = 312, Descricao = "312 - TÉCNICOS EM CONSTRUÇÃO CIVIL, DE EDIFICAÇÕES E OBRAS DE INFRAESTRUTURA" },
            new EnumItem { Id = 313, Descricao = "313 - TÉCNICOS EM ELETROELETRÔNICA E FOTÔNICA" },
            new EnumItem { Id = 314, Descricao = "314 - TÉCNICOS EM METALMECÂNICA" },
            new EnumItem { Id = 316, Descricao = "316 - TÉCNICOS EM MINERALOGIA E GEOLOGIA" },
            new EnumItem { Id = 317, Descricao = "317 - TÉCNICOS EM INFORMÁTICA" },
            new EnumItem { Id = 318, Descricao = "318 - DESENHISTAS TÉCNICOS E MODELISTAS" },
            new EnumItem { Id = 319, Descricao = "319 - OUTROS TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS, QUÍMICAS, ENGENHARIA E AFINS" },
            new EnumItem { Id = 320, Descricao = "320 - TÉCNICOS EM BIOLOGIA" },
            new EnumItem { Id = 321, Descricao = "321 - TÉCNICOS DA PRODUÇÃO AGROPECUÁRIA" },
            new EnumItem { Id = 322, Descricao = "322 - TÉCNICOS DA CIÊNCIA DA SAÚDE HUMANA" },
            new EnumItem { Id = 323, Descricao = "323 - TÉCNICOS DA CIÊNCIA DA SAÚDE ANIMAL" },
            new EnumItem { Id = 324, Descricao = "324 - TÉCNICOS EM OPERAÇÃO DE EQUIPAMENTOS E INSTRUMENTOS DE DIAGNÓSTICO" },
            new EnumItem { Id = 325, Descricao = "325 - TÉCNICOS DE BIOQUÍMICA E DA BIOTECNOLOGIA" },
            new EnumItem { Id = 328, Descricao = "328 - TÉCNICOS EM NECRÓPSIA E TAXIDERMISTAS" },
            new EnumItem { Id = 331, Descricao = "331 - PROFESSORES DE NÍVEL MÉDIO NA EDUCAÇÃO INFANTIL, NO ENSINO FUNDAMENTAL E NO PROFISSIONALIZANTE" },
            new EnumItem { Id = 332, Descricao = "332 - PROFESSORES LEIGOS NO ENSINO FUNDAMENTAL E NO PROFISSIONALIZANTE" },
            new EnumItem { Id = 333, Descricao = "333 - INSTRUTORES E PROFESSORES DE ESCOLAS LIVRES" },
            new EnumItem { Id = 334, Descricao = "334 - INSPETORES DE ALUNOS E AFINS" },
            new EnumItem { Id = 341, Descricao = "341 - TÉCNICOS EM NAVEGAÇÃO AÉREA, MARÍTIMA E FLUVIAL" },
            new EnumItem { Id = 342, Descricao = "342 - TÉCNICOS EM TRANSPORTES (LOGÍSTICA)" },
            new EnumItem { Id = 351, Descricao = "351 - TÉCNICOS DAS CIÊNCIAS ADMINISTRATIVAS" },
            new EnumItem { Id = 352, Descricao = "352 - TÉCNICOS DE INSPEÇÃO, FISCALIZAÇÃO E COORDENAÇÃO ADMINISTRATIVA" },
            new EnumItem { Id = 353, Descricao = "353 - TÉCNICOS DE NÍVEL MÉDIO EM OPERAÇÕES FINANCEIRAS" },
            new EnumItem { Id = 354, Descricao = "354 - TÉCNICOS DE NIVEL MÉDIO EM OPERAÇÕES COMERCIAIS" },
            new EnumItem { Id = 371, Descricao = "371 - TÉCNICOS DE SERVIÇOS CULTURAIS" },
            new EnumItem { Id = 372, Descricao = "372 - TÉCNICOS EM OPERAÇÃO DE CÂMARA FOTOGRÁFICA , CINEMA E DE TELEVISÃO" },
            new EnumItem { Id = 373, Descricao = "373 - TÉCNICOS EM OPERAÇÃO DE EMISSORAS DE RÁDIO, SISTEMAS DE TELEVISÃO E DE PRODUTORAS DE VÍDEO" },
            new EnumItem { Id = 374, Descricao = "374 - TÉCNICOS EM OPERAÇÃO DE APARELHOS DE SONORIZAÇÃO, CENOGRAFIA E PROJEÇÃO" },
            new EnumItem { Id = 375, Descricao = "375 - DECORADORES E VITRINISTAS" },
            new EnumItem { Id = 376, Descricao = "376 - ARTISTAS DE ARTES POPULARES E MODELOS" },
            new EnumItem { Id = 377, Descricao = "377 - ATLETAS, DESPORTISTAS E AFINS" },
            new EnumItem { Id = 391, Descricao = "391 - TÉCNICOS DE NIVEL MÉDIO EM OPERAÇÕES INDUSTRIAIS" },
            new EnumItem { Id = 395, Descricao = "395 - TÉCNICOS DE APOIO EM PESQUISA E DESENVOLVIMENTO" },
            new EnumItem { Id = 410, Descricao = "410 - SUPERVISORES DE SERVIÇOS ADMINISTRATIVOS (Exceto de atendimento ao público)" },
            new EnumItem { Id = 411, Descricao = "411 - ESCRITURÁRIOS EM GERAL, AGENTES, ASSISTENTES E AUXILIARES ADMINISTRATIVOS" },
            new EnumItem { Id = 412, Descricao = "412 - SECRETÁRIOS DE EXPEDIENTE E OPERADORES DE MÁQUINAS DE ESCRITÓRIOS" },
            new EnumItem { Id = 413, Descricao = "413 - ESCRITURÁRIOS CONTÁBEIS E DE FINANÇAS" },
            new EnumItem { Id = 414, Descricao = "414 - ESCRITURÁRIOS DE CONTROLE DE MATERIAIS E DE APOIO À PRODUÇÃO" },
            new EnumItem { Id = 415, Descricao = "415 - AUXILIARES DE SERVIÇOS DE BIBLIOTECA, DOCUMENTAÇÃO E CORREIOS" },
            new EnumItem { Id = 420, Descricao = "420 - SUPERVISORES DE ATENDIMENTO AO PÚBLICO" },
            new EnumItem { Id = 421, Descricao = "421 - CAIXAS, BILHETEIROS E AFINS" },
            new EnumItem { Id = 422, Descricao = "422 - TRABALHADORES DE INFORMAÇÕES AO PÚBLICO" },
            new EnumItem { Id = 423, Descricao = "423 - DESPACHANTES" },
            new EnumItem { Id = 424, Descricao = "424 - ENTREVISTADORES, RECENSEADORES E AFINS" },
            new EnumItem { Id = 510, Descricao = "510 - SUPERVISORES DOS SERVIÇOS" },
            new EnumItem { Id = 511, Descricao = "511 - TRABALHADORES DOS SERVIÇOS DE TRANSPORTE E TURISMO" },
            new EnumItem { Id = 512, Descricao = "512 - TRABALHADORES DOS SERVIÇOS DOMÉSTICOS EM GERAL" },
            new EnumItem { Id = 513, Descricao = "513 - TRABALHADORES DOS SERVIÇOS DE HOTELARIA E ALIMENTAÇÃO" },
            new EnumItem { Id = 514, Descricao = "514 - TRABALHADORES NOS SERVIÇOS DE ADMINISTRAÇÃO, CONSERVAÇÃO E MANUTENÇÃO DE EDIFÍCIOS E LOGRADOUROS" },
            new EnumItem { Id = 515, Descricao = "515 - TRABALHADORES DOS SERVIÇOS DE SAÚDE" },
            new EnumItem { Id = 516, Descricao = "516 - TRABALHADORES NOS SERVIÇOS DE EMBELEZAMENTO E CUIDADOS PESSOAIS" },
            new EnumItem { Id = 517, Descricao = "517 - TRABALHADORES NOS SERVIÇOS DE PROTEÇÃO E SEGURANÇA" },
            new EnumItem { Id = 519, Descricao = "519 - OUTROS TRABALHADORES DE SERVIÇOS DIVERSOS" },
            new EnumItem { Id = 520, Descricao = "520 - SUPERVISORES DE VENDAS E DE PRESTAÇÃO DE SERVIÇOS" },
            new EnumItem { Id = 521, Descricao = "521 - VENDEDORES E DEMONSTRADORES" },
            new EnumItem { Id = 522, Descricao = "522 - REPOSITORES E REMARCADORES DO COMÉRCIO" },
            new EnumItem { Id = 523, Descricao = "523 - INSTALADORES DE PRODUTOS E ACESSÓRIOS" },
            new EnumItem { Id = 524, Descricao = "524 - VENDEDORES A DOMICÍLIO, AMBULANTES E EM BANCAS" },
            new EnumItem { Id = 611, Descricao = "611 - PRODUTORES AGROPECUÁRIOS EM GERAL" },
            new EnumItem { Id = 612, Descricao = "612 - PRODUTORES AGRÍCOLAS" },
            new EnumItem { Id = 613, Descricao = "613 - PRODUTORES EM PECUÁRIA" },
            new EnumItem { Id = 620, Descricao = "620 - SUPERVISORES NA EXPLORAÇÃO AGROPECUÁRIA" },
            new EnumItem { Id = 621, Descricao = "621 - TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA EM GERAL" },
            new EnumItem { Id = 622, Descricao = "622 - TRABALHADORES AGRÍCOLAS" },
            new EnumItem { Id = 623, Descricao = "623 - TRABALHADORES NA PECUÁRIA" },
            new EnumItem { Id = 630, Descricao = "630 - SUPERVISORES NA EXPLORAÇÃO FLORESTAL E PESCA" },
            new EnumItem { Id = 631, Descricao = "631 - PESCADORES E CAÇADORES" },
            new EnumItem { Id = 632, Descricao = "632 - EXTRATIVISTAS FLORESTAIS" },
            new EnumItem { Id = 641, Descricao = "641 - TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA" },
            new EnumItem { Id = 642, Descricao = "642 - TRABALHADORES DA MECANIZAÇÃO FLORESTAL" },
            new EnumItem { Id = 643, Descricao = "643 - TRABALHADORES DA IRRIGAÇÃO E DRENAGEM" },
            new EnumItem { Id = 710, Descricao = "710 - SUPERVISORES DA EXTRAÇÃO MINERAL E DA CONSTRUÇÃO CIVIL" },
            new EnumItem { Id = 711, Descricao = "711 - TRABALHADORES DA EXTRAÇÃO MINERAL" },
            new EnumItem { Id = 712, Descricao = "712 - TRABALHADORES DE BENEFICIAMENTO DE MINÉRIOS E PEDRAS ORNAMENTAIS" },
            new EnumItem { Id = 715, Descricao = "715 - TRABALHADORES DA CONSTRUÇÃO CIVIL E OBRAS PÚBLICAS" },
            new EnumItem { Id = 716, Descricao = "716 - TRABALHADORES DE ACABAMENTO DE OBRAS" },
            new EnumItem { Id = 717, Descricao = "717 - AJUDANTES DE OBRAS" },
            new EnumItem { Id = 720, Descricao = "720 - SUPERVISORES DA TRANSFORMAÇÃO DE METAIS E DE COMPÓSITOS" },
            new EnumItem { Id = 721, Descricao = "721 - TRABALHADORES DE USINAGEM DE METAIS E DE COMPÓSITOS" },
            new EnumItem { Id = 722, Descricao = "722 - TRABALHADORES DE CONFORMAÇÃO DE METAIS E DE COMPÓSITOS" },
            new EnumItem { Id = 723, Descricao = "723 - TRABALHADORES DE TRATAMENTO TÉRMICO E DE SUPERFÍCIES DE METAIS E DE COMPÓSITOS" },
            new EnumItem { Id = 724, Descricao = "724 - TRABALHADORES DE MONTAGEM DE TUBULAÇÕES, ESTRUTURAS METÁLICAS E DE COMPÓSITOS" },
            new EnumItem { Id = 725, Descricao = "725 - MONTADORES DE MÁQUINAS E APARELHOS MECÂNICOS" },
            new EnumItem { Id = 730, Descricao = "730 - SUPERVISORES DE MONTAGENS E INSTALAÇÕES ELETROELETRÔNICAS" },
            new EnumItem { Id = 731, Descricao = "731 - MONTADORES E INSTALADORES DE EQUIPAMENTOS ELETROELETRÔNICOS EM GERAL" },
            new EnumItem { Id = 732, Descricao = "732 - INSTALADORES E REPARADORES DE LINHAS E CABOS ELÉTRICOS E DE COMUNICAÇÕES" },
            new EnumItem { Id = 740, Descricao = "740 - SUPERVISORES DA MECÂNICA DE PRECISÃO E INSTRUMENTOS MUSICAIS" },
            new EnumItem { Id = 741, Descricao = "741 - MONTADORES E AJUSTADORES DE INSTRUMENTOS DE PRECISÃO" },
            new EnumItem { Id = 742, Descricao = "742 - MONTADORES E AJUSTADORES DE INSTRUMENTOS MUSICAIS" },
            new EnumItem { Id = 750, Descricao = "750 - SUPERVISORES DE JOALHERIA, VIDRARIA, CERÂMICA E AFINS" },
            new EnumItem { Id = 751, Descricao = "751 - JOALHEIROS E OURIVES" },
            new EnumItem { Id = 752, Descricao = "752 - VIDREIROS, CERAMISTAS E AFINS" },
            new EnumItem { Id = 760, Descricao = "760 - SUPERVISORES NAS INDÚSTRIAS TÊXTIL, DO CURTIMENTO, DO VESTUÁRIO E DAS ARTES GRÁFICAS" },
            new EnumItem { Id = 761, Descricao = "761 - TRABALHADORES DAS INDUSTRIAS TÊXTEIS" },
            new EnumItem { Id = 762, Descricao = "762 - TRABALHADORES DO TRATAMENTO DE COUROS E PELES" },
            new EnumItem { Id = 763, Descricao = "763 - TRABALHADORES DA CONFECÇÃO DE ROUPAS" },
            new EnumItem { Id = 764, Descricao = "764 - TRABALHADORES DA CONFECÇÃO DE CALÇADOS" },
            new EnumItem { Id = 765, Descricao = "765 - TRABALHADORES DA CONFECÇÃO DE ARTEFATOS DE TECIDOS E COUROS" },
            new EnumItem { Id = 766, Descricao = "766 - TRABALHADORES DA PRODUÇÃO GRÁFICA" },
            new EnumItem { Id = 768, Descricao = "768 - TRABALHADORES ARTESANAIS DAS ATIVIDADES TÊXTEIS, DO VESTUÁRIO E DAS ARTES GRÁFICAS" },
            new EnumItem { Id = 770, Descricao = "770 - SUPERVISORES EM INDÚSTRIA DE MADEIRA, MOBILIÁRIO E DA CARPINTARIA VEICULAR" },
            new EnumItem { Id = 771, Descricao = "771 - MARCENEIROS E AFINS" },
            new EnumItem { Id = 772, Descricao = "772 - TRABALHADORES DA PREPARAÇÃO DA MADEIRA" },
            new EnumItem { Id = 773, Descricao = "773 - TRABALHADORES DA TRANSFORMAÇÃO DA MADEIRA E DA FABRICAÇÃO DO MOBILIÁRIO" },
            new EnumItem { Id = 774, Descricao = "774 - TRABALHADORES DE MONTAGEM DE MÓVEIS E ARTEFATOS DE MADEIRA" },
            new EnumItem { Id = 775, Descricao = "775 - TRABALHADORES EM ACABAMENTO DE MADEIRA E DE MOBILIÁRIO" },
            new EnumItem { Id = 776, Descricao = "776 - TRABALHADORES ARTESANAIS DA MADEIRA E DO MOBILIÁRIO" },
            new EnumItem { Id = 777, Descricao = "777 - TRABALHADORES DA CARPINTARIA VEICULAR" },
            new EnumItem { Id = 780, Descricao = "780 - SUPERVISORES DE TRABALHADORES DE EMBALAGEM E ETIQUETAGEM" },
            new EnumItem { Id = 781, Descricao = "781 - OPERADORES DE ROBÔS E EQUIPAMENTOS ESPECIAIS" },
            new EnumItem { Id = 782, Descricao = "782 - CONDUTORES DE VEÍCULOS E OPERADORES DE EQUIPAMENTOS DE ELEVAÇÃO E DE MOVIMENTAÇÃO DE CARGAS" },
            new EnumItem { Id = 783, Descricao = "783 - TRABALHADORES DE MANOBRAS SOBRE TRILHOS E MOVIMENTAÇÃO E CARGAS" },
            new EnumItem { Id = 784, Descricao = "784 - EMBALADORES E ALIMENTADORES DE PRODUÇÃO" },
            new EnumItem { Id = 791, Descricao = "791 - TRABALHADORES DO ARTESANATO URBANO E RURAL" },
            new EnumItem { Id = 810, Descricao = "810 - SUPERVISORES DE PRODUÇÃO, EM INDÚSTRIAS QUÍMICAS, PETROQUÍMICAS E AFINS" },
            new EnumItem { Id = 811, Descricao = "811 - OPERADORES DE INSTALAÇÕES EM INDÚSTRIAS QUÍMICAS, PETROQUÍMICAS E AFINS" },
            new EnumItem { Id = 812, Descricao = "812 - TRABALHADORES DA FABRICAÇÃO DE MUNIÇÃO E EXPLOSIVOS QUÍMICOS" },
            new EnumItem { Id = 813, Descricao = "813 - OPERADORES DE OUTRAS INSTALAÇÕES QUÍMICAS, PETROQUÍMICAS E AFINS" },
            new EnumItem { Id = 818, Descricao = "818 - OPERADORES DE OPERAÇÃO UNITÁRIA DE LABORATÓRIO (TRANSVERSAL PARA TODA INDÚSTRIA DE PROCESSOS)" },
            new EnumItem { Id = 820, Descricao = "820 - SUPERVISORES DE PRODUÇÃO EM INDÚSTRIAS SIDERÚRGICAS" },
            new EnumItem { Id = 821, Descricao = "821 - OPERADORES DE INSTALAÇÕES E EQUIPAMENTOS DE PRODUÇÃO DE METAIS E LIGAS- PRIMEIRA FUSÃO" },
            new EnumItem { Id = 822, Descricao = "822 - OPERADORES DE INSTALAÇÕES E EQUIPAMENTOS DE PRODUÇÃO DE METAIS E LIGAS- SEGUNDA FUSÃO" },
            new EnumItem { Id = 823, Descricao = "823 - TRABALHADORES DE INSTALAÇÕES E EQUIPAMENTOS DE MATERIAL DE CONSTRUÇÃO, CERÂMICA E VIDRO" },
            new EnumItem { Id = 828, Descricao = "828 - TRABALHADORES ARTESANAIS DA SIDERURGIA E DE MATERIAIS DE CONSTRUÇÃO" },
            new EnumItem { Id = 830, Descricao = "830 - SUPERVISORES DA FABRICAÇÃO DE CELULOSE E PAPEL" },
            new EnumItem { Id = 831, Descricao = "831 - TRABALHADORES DA PREPARAÇÃO DE PASTA DE PAPEL" },
            new EnumItem { Id = 832, Descricao = "832 - TRABALHADORES DA FABRICAÇÃO DE PAPEL" },
            new EnumItem { Id = 833, Descricao = "833 - CONFECCIONADORES DE PRODUTOS DE PAPEL E PAPELÃO" },
            new EnumItem { Id = 840, Descricao = "840 - SUPERVISORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO" },
            new EnumItem { Id = 841, Descricao = "841 - OPERADORES DE EQUIPAMENTOS NA PREPARAÇÃO DE ALIMENTOS E BEBIDAS" },
            new EnumItem { Id = 842, Descricao = "842 - OPERADORES NA PREPARAÇÃO DE FUMO E NA FABRICAÇÃO DE CHARUTOS E CIGARROS" },
            new EnumItem { Id = 848, Descricao = "848 - TRABALHADORES ARTESANAIS NA AGROINDÚSTRIA, NA INDÚSTRIA DE ALIMENTOS E DO FUMO" },
            new EnumItem { Id = 860, Descricao = "860 - SUPERVISORES DA PRODUÇÃO DE UTILIDADES" },
            new EnumItem { Id = 861, Descricao = "861 - OPERADORES NA GERAÇÃO E DISTRIBUIÇÃO DE ENERGIA (CENTRAIS HIDRELÉTRICAS, TERMELÉTRICAS E NUCLEARES)" },
            new EnumItem { Id = 862, Descricao = "862 - OPERADORES DE UTILIDADES" },
            new EnumItem { Id = 871, Descricao = "871 - OPERADORES DE OUTRAS INSTALAÇÕES INDUSTRIAIS" },
            new EnumItem { Id = 910, Descricao = "910 - SUPERVISORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO MECÂNICA" },
            new EnumItem { Id = 911, Descricao = "911 - MECÂNICOS DE MANUTENÇÃO DE MÁQUINAS E EQUIPAMENTOS INDUSTRIAIS, COMERCIAIS E RESIDENCIAIS" },
            new EnumItem { Id = 913, Descricao = "913 - MECÂNICOS DE MANUTENÇÃO DE MÁQUINAS PESADAS E EQUIPAMENTOS AGRÍCOLAS" },
            new EnumItem { Id = 914, Descricao = "914 - MECÂNICOS DE MANUTENÇÃO VEICULAR" },
            new EnumItem { Id = 915, Descricao = "915 - REPARADORES DE INSTRUMENTOS E EQUIPAMENTOS DE PRECISÃO" },
            new EnumItem { Id = 919, Descricao = "919 - OUTROS TRABALHADORES NA REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS" },
            new EnumItem { Id = 950, Descricao = "950 - SUPERVISORES DE MANUTENÇÃO ELETROELETRÔNICA E ELETROMECÂNICA" },
            new EnumItem { Id = 951, Descricao = "951 - ELETRICISTAS ELETRÔNICOS DE MANUTENÇÃO INDUSTRIAL, COMERCIAL E RESIDENCIAL" },
            new EnumItem { Id = 953, Descricao = "953 - ELETRICISTAS ELETRÔNICOS DE MANUTENÇÃO VEICULAR" },
            new EnumItem { Id = 954, Descricao = "954 - MANTENEDORES ELETROMECÂNICOS" },
            new EnumItem { Id = 991, Descricao = "991 - OUTROS TRABALHADORES DA CONSERVAÇÃO E MANUTENÇÃO (EXCETO TRABALHADORES ELEMENTARES)" },
            new EnumItem { Id = 992, Descricao = "992 - TRABALHADORES ELEMENTARES DA MANUTENÇÃO" }
        ];
    }
}